#!/bin/sh

# ldconfig

if [ ! -f /etc/gnucash/config ]; then
	touch /etc/gnucash/config
fi

if [ "$1" = "configure" ]; then
	guile-1.6 -c "(use-modules (ice-9 slib)) (require 'new-catalog)"
fi

#DEBHELPER#
